### ISSUE TITLE
Weird behavior when undoing a card

### ISSUE THREAD

**Issue by ferdieperante** [brownbat/autoEaseFactor#13]
I use undo options fairly often. I have noticed that the intervals changed depending on the rating of the latest rating of the card -- just before undoing. I am unsure which behavior is normal and if the behavior is normal at all. It doesn't bother me a lot, but I think that it could potentially have some significant effects in the long term.

**Comment by brownbat** [comment]
Hmm, interesting. 

I noticed something like this in earlier versions, I thought it was fixed by a recent version. 

For example, undoing and repeating a review with fail, then pass, then fail, then pass:

![image](https://user-images.githubusercontent.com/26754/93217587-dd34c200-f72e-11ea-8856-01bb1c952c0e.png)


Those all give the same calculations and recommended ease (and I clearly need to rework this card!).

If you would be willing to help test -- pick a card and undo and redo a few times, grabbing an image of the stats tooltip after each result. (If you're on windows you can use win+shift+s to grab just that area, makes it a little quicker, then I just pasted those together into paint.) That would be really helpful data for me to investigate further.

I will say even when this was happening, because of the feedback systems involved, small adjustments do get washed out over time, because the algorithm is constantly homing in on the correct values, different starting values will converge over time, if that makes you feel any better. Would still like to fix if I can diagnose of course.

**Comment by brownbat** [comment]
I'm going to close for now. Please reopen though if you see anything like this happening again. Thanks for the feedback!
