### ISSUE TITLE
Needs tests

### ISSUE THREAD

**Issue by brownbat** [brownbat/autoEaseFactor#2]
Writing tests with fake review data that interfaces with the main Anki program has been very difficult.

It could be a helpful half-measure to just write a simulator that could read some fake review data and let people compare how this or the default algorithm would work.

**Comment by brownbat** [comment]
I've added a tests.py file you can run from the command line as a halfway step here. It's not automated, you kind of have to pop it open to tweak the main variables then run it from the command line. It will show the results of a card with the old algorithm and with this algorithm side by side. Early findings: this usually gets much closer to the targeted success rate, but the overall number of reviews doesn't change that dramatically. (There are only so many reviews per card in a given year, so it's hard to shift that too much.) In some cases you will do an extra review in the first year, in other cases one fewer, it's hard to predict, but in almost every case it gets much closer to your targeted success rate for the same number of reviews (so you feel like you're challenged but aren't failing a bunch in a row).

Overall the biggest advantage of the add-on seems to be simplifying the review process, the effects on reps are there, but fairly small all things considered.

I'd like to model other types of cards and run other test cases, but it involves figuring out how a hypothetical card should perform over time, which involves some non-trivial assumptions and modeling of how memory works.

Will keep giving it some thought.

**Comment by brownbat** [comment]
One thing that I'm realizing, when I fail a card, one of two completely different things is probably happening: 

1. It's a momentary blip. Putting me back at my last ivl is probably the right way to go.
2. I've actually forgotten that card, it just didn't stick. There are varying levels of severity here, but it probably should be reset close to relearning. (This is the default behavior for anki.)

esharpard wrote about setting a better new interval after a lapse [here](https://eshapard.github.io/anki/anki-new-interval-after-a-lapse.html). I think that's right in general, you could have a much more generous interval for most lapsed cards and be in a good place. But I think you might be able to get more fidelity by splitting cards into two groups, the true lapses, and the momentary blips.

So I'd really like a lapse to go into a test mode that helps distinguish between these two cases.

Maybe test again in 3-7 days, after we've left short term memory.
If I get it on that second relearning step, send it back to the queue with almost the same ivl it had before, maybe lower ease only slightly.
If I fail that lapse test, then that means trouble. Only in those cases, start over at the beginning of relearning, because this is a true lapse.

I don't know if I can implement in this add-on, or if that needs a separate add-on, but that seems like the next major area for efficiency gains after this testing.

**Comment by buster-blue** [comment]
I think we can reutilize deck options here. Here's how I think it should be done:

When a card lapses, have the card scheduled for a review the next day. (I think 1 day is enough time for a card to leave working and short term memory, but if you feel otherwise, a config option for it would be appreciated.) when this "testing review" comes up, 2 different things can happen. If a card is answered correctly this time, the card uses the "new interval" setting to set its next review, since that means that the card is probably still remembered and just needs to be adjusted. If the card is answered incorrectly again, then it ignores the new interval, and instead it puts the card back into learning and uses the learning steps in the deck settings, since this probably means that the card was really forgotten, and it needs to be given similar treatment to a new card. When the card is finished with learning, it just uses the graduating interval for it's next interval, like it's a new learning card that just graduated into a review card.

The idea is that, since using the steps and the new interval together don't really make sense (since the new interval won't change to respond to multiple failures in relearning if that happens) the testing review will choose whether a card was really forgotten, or just had a temporary lapse, and use steps or the new interval respectively.

Also, if it's possible for this feature to be a separate add-on while still playing nice with this one, then I think making it separate would be better. I could see many people preferring this way of handling lapses, without wanting the entire algorithm to change with it.

**Comment by brownbat** [comment]
Yeah, agree about it being a separate add-on, tackles a different problem completely.

I think that's the right sketch of how it should work, and an option to control the retesting interval sounds like a smart idea.

**Comment by galantra** [comment]
> Overall the biggest advantage of the add-on seems to be simplifying the review process, the effects on reps are there, but fairly small all things considered.

I fully agree! It's a considerable time-saver, and helps focus on the content instead of the grading possibilities.

**Comment by galantra** [comment]
> esharpard wrote about setting a better new interval after a lapse [here](https://eshapard.github.io/anki/anki-new-interval-after-a-lapse.html). I think that's right in general, you could have a much more generous interval for most lapsed cards and be in a good place. But I think you might be able to get more fidelity by splitting cards into two groups, the true lapses, and the momentary blips.
> 
> So I'd really like a lapse to go into a test mode that helps distinguish between these two cases.
> 
> Maybe test again in 3-7 days, after we've left short term memory.
> If I get it on that second relearning step, send it back to the queue with almost the same ivl it had before, maybe lower ease only slightly.
> If I fail that lapse test, then that means trouble. Only in those cases, start over at the beginning of relearning, because this is a true lapse.
> 
> I don't know if I can implement in this add-on, or if that needs a separate add-on, but that seems like the next major area for efficiency gains after this testing.

Although [scheduler: Dynamic Lapse Interval (alpha)](https://ankiweb.net/shared/info/678594073) doesn't do exactly what you discussed, I think it is a relevant add-on that I'd like to direct attention to.

**Comment by galantra** [comment]
> I think 1 day is enough time for a card to leave working and short term memory, but if you feel otherwise, a config option for it would be appreciated.

I do think otherwise – I sometimes have the problem of accidentally seeing the answer to a card before I have made a sufficient effort to recall it. In these cases, I bury the card. 1 day is not enough to really remove it from short-term memory. Therefore I use the ReMemorize add-on. For cards with a short interval (~ under 6 months or sth like that), I bury it for 7 days. Cards with a longer interval get buried for 30 days.

> If the card is answered incorrectly again, then it ignores the new interval, and instead it puts the card back into learning and uses the learning steps in the deck settings, since this probably means that the card was really forgotten, and it needs to be given similar treatment to a new card.

In my experience, (real) lapses (or, forgotten cards, if you will), are not the same as totally new cards. They are often easier. In my opinion, these two groups shouldn't be treated the same.

Others' opinions can of course be different.

> When the card is finished with learning, it just uses the graduating interval for it's next interval, like it's a new learning card that just graduated into a review card.

I'd like to emphasize that in this case, in my opinion, _experimentalCardEaseFactor_ should still take into account the whole history of the card (which hopefully remains stored in the card info, even after this novel relearning which you described)..

**Comment by brownbat** [comment]
The simulator.py accomplishes most of the original goal here.
