### ISSUE TITLE
Min ease lower than 100 % (min_ease < 1000)

### ISSUE THREAD

**Issue by aleksejrs** [brownbat/autoEaseFactor#28]
Does it make sense to do that? It could help sorting the unfailed cards by ease.

**Comment by brownbat** [comment]
I have done it, and it does help me find my hardest cards for rework, so it had some advantages. 

But note that due to another issue, #24 -- in the last half we discovered Anki resets your ease to a minimum of 130% when graduating from relearning. 

Since relearning steps are manually set in options, a lower than 100% ease won't ever affect scheduling. (But it will let you find your weakest cards that are still in relearning, you'll just have to look at all the 130% cards too, it won't be clear which graduated cards should technically be below 130 after they graduated.)
