### ISSUE TITLE
Recommended learning (New card) steps?

### ISSUE THREAD

**Issue by roboticsbrian** [brownbat/autoEaseFactor#29]
When using this add-on, do you have a recommendation for the new card steps to use? Prior to this, I had been using eshapard's long steps (15 2160 10080 40320). Do you recommend reverting to a simpler/shorter set of learning steps e.g. 1 10 and letting the algorithm adjust the ease from the beginning?

**Comment by brownbat** [comment]
Inspired by eshapard, I originally used his long steps too. I was having very poor second step success rates for some cards. I tried shorter steps, and believe those work best for me. I like letting the algorithm (ie, my past performance) take over as soon as possible.

I'm using this more for vocab. It's possible that a very fixed schedule may work better for more conceptual cards -- essentially spreading your learning over a month, but forcing yourself not to spend any more time learning than the minimum. Then the algorithm starts judging you in month 2.

I like performance-based scheduling from day one though. Cards are all different, some are hard and some are easy, best to customize your reps to that.

Have to note, [Interval Booster](https://ankiweb.net/shared/info/1602224446) is an add-on by another developer that tries to automatically set the best **initial** interval by learning how you do with other cards. I haven't extensively tested it but I really like the idea.

**Comment by aleksejrs** [comment]
I am currently tweaking my steps based on [Learning Step and Review Interval Retention](https://ankiweb.net/shared/info/1949865265). Since I am mostly learning siblings of the known cards (MorphMan's mm_comprehension), I recently removed the second step from both Learn and Relearn, but it'll be a few weeks until I find the right only step and see what the Graduation retention becomes.

**Comment by galantra** [comment]
I used to have long steps, up to over a month, too. I also used and still use autoLearningSteps.

However, a few weeks in after downloading AutoEaseFactor, I followed @brownbat's advice and tested shorter steps out.

Nowadays I still use autoLearningSteps but I have settles on these settings in __init__.py:

```
for i in range(10):
                l = int(1440*ease**i)
                if l < 3744:
```
3744 min is equivalent to 2.6 days.

The result is that my graduating interval occurs much sooner (at 2 days or 6 days, depending on the deck's initial ease (I use AvgEase for the deck starting ease)).

I want AutoEaseFactor to determine the intervals early on, because it optimizes the intervals, saving time at minimal retention cost. I set the desired success rate to 80 % to save more time. 

Supermemo has [an article](https://www.supermemo.com/archives1990-2015/articles/theory#Retention) about this.

> ![](https://static.supermemo.com/old_articles/images/ol_fig6.gif)
> 

>     The greatest overall increase in the optimal interval can be observed for the forgetting index of about 20%. The overall increase takes into the consideration the fact that for forgotten items, the optimal interval decreases. Therefore, for the forgetting index greater than 20%, the positive effect of long intervals on memory resulting from the spacing effect is offset by the increasing number of forgotten items.
>     The greatest overall knowledge acquisition rate is obtained for the forgetting index of about 20-30% (see Figure 3). This results from the trade-off between reducing the repetition workload and increasing the relearning workload as the forgetting index progresses upward. In other words, high values of the forgetting index result in longer intervals, but the gain is offset by an additional workload coming from a greater number of forgotten items that have to be relearned.
>
