### ISSUE TITLE
Only Use Reviews (not learning steps or reschedules)

### ISSUE THREAD

**Issue by brownbat** [brownbat/autoEaseFactor#4]
This is currently an intentional design decision, to use as much data as possible to inform what the ease should be, but some people have commented that they would prefer to be able to restrict the types of reps to consider to only review steps, like eshaphard's original design.

The leash setting can help prevent learning steps from having too much early impact, setting it lower, to 10 or 50, will make the ease adjustments wait until you've gathered enough data from reps to be sure where the ease should be.

There have been multiple requests for this though so will consider it long term.

**Comment by buster-blue** [comment]
Hey, I'm the guy who made that negative (now positive) review on the addon page.

I was unaware that making reviews in the learning phase was intentional. When you mentioned "early" reviews, I thought that you meant reviews while the card was young, not still in learning.

The main problem I have with learning reviews being considered valid data, is that it's at odds with the Anki philosophy of how learning reviews are supposed to be treated. Since card retention is usually unstable when it's first being learned, the retention ratio of a card in learning isn't indicative of the ratio it'll have once it's a proper review card, especially a mature one. I can see that for myself in Anki's stats page, where my learning retention is about 70%, but my young and mature retention are both about 80%.

Anyway, that's just my thoughts on the matter. I'll try lowering the leash to 10 like you suggested to see if that helps. Maybe with a lower leash, the learning reviews will be beneficial data.

**Comment by brownbat** [comment]
Really appreciate the feedback, and sorry for the unexpected results!

> When you mentioned "early" reviews...

You're right, I should say "reps" to refer to all of those, and also call
out learning explicitly so people aren't caught off guard.

On philosophy...

> learning reviews being considered valid data, is ... at odds with the
Anki philosophy

Early reps are definitely low quality data, agree. I hadn't quite realized
it, but I guess I am diverging from the Anki philosophy.

The challenge I ran into is that anyone can set any number of learning
steps they like. Someone could have 2, someone else could have 10. But your
memory won't be able to tell the difference, it just gradually performs
more predictably over time.

So I started seeing this more as a curve. The first rep (learning) is the
lowest quality. Each next rep (whether learning or review) provides
slightly better data than the last.

With the add-on, I want to ideally juggle a few things:
(1) enable early performance-based feedback (for those who want the
algorithm to take over as soon as possible),
(2) have settings that limit that (for those who want it to wait for better
data first), and,
(3) make sure the most recent reps have the most weight on the settings.

There's a little tension between these, but I think we can thread the
needle.

For (3) -- The moving average definitely helps. The algorithm "self heals."
Early data is low quality, but since the newest rep is weighted heavily in
the calculations, it has a much higher influence on intervals, and the
oldest data gets pushed out over time.

For (2) -- I think clarifying the settings and being more explicit in the
write up will help keep people from being caught off guard. I'll still keep
an eye on this to see if I need to make it even more conservative in later
versions.

With those safeguards in place, I think I can still wring a tiny bit of
data from the learning steps and be ok to support (1). But... it's worth
testing.

So I also worked on a testing file today, to try to compare performance
with the old and new algorithm. It's not perfect yet. I need to model a lot
more cases. But it's a start. Once that's in better shape, people will be
able to see their expected reviews and success rates under both systems and
compare for themselves.

I really do appreciate the feedback, it inspired me to think a lot more
about this today, thanks.

Let me know how it goes,

Thomas

**Comment by buster-blue** [comment]
Once you go through with this change (I assume you're going through with it, but let me know otherwise) I'd really like it if you could disable the "yesno" feature for learning cards, so that we can use hard and easy answers on them again. Since they wouldn't be considered valid data anymore, it wouldn't matter how you answered the cards in learning anyway.

Should this be its own issue?

**Comment by brownbat** [comment]
I've added an option for four-button mode.

Still refining the testing package.

**Comment by galantra** [comment]
Thanks for the 4 button mode. I use ReMemorize and ReMemorize Buttons, so that I can send cards that I already know well on the first encounter (especially language learning) into the far future, e.g. 1 year ahead.

Some more thoughts and experiences:

Apart from that, I also profit from having the regular easy button, because in some topics my retention rate is over 90% – and therefore I should use higher ("easy") intervals rather than shorter ("good") intervals there. I am aware of "ease hell" and therefore never use the "hard" button.

The fact that this method of mine adds a bigger range of decisions to the game and that this can be bad is something I should give more thought to. I have indeed made the observation that I often hit "Ctrl+Z" after a "good" rating to revert the rating to "easy", and this costs me a considerable amount of time.

**Comment by brownbat** [comment]
Closely related: a request on AnkiWeb to disable this for filtered decks.

Adding these options is important, just haven't quite gotten to it yet.

**Comment by sourstripe** [comment]
> Closely related: a request on AnkiWeb to disable this for filtered decks.
> 
> Adding these options is important, just haven't quite gotten to it yet.

Or just disable for filtered decks with the reschedule cards option turned off. Since they are just a quick, random review

**Comment by brownbat** [comment]
Latest version lets you set "reviews only" in options.

I put a warning in the config.md. You've all heard my spiel, this is reducing the data the algorithm learn from, so I worry about it leading to less accurate results. But users can make their own call. The option is there for anybody who really wants to use it.

I thought about letting people specify different settings for every possible state of a card, but that turned out to be a bit too complex at this time. I'm hoping "reviews_only" will cover 99% of cases people are looking to solve for.

Thanks to everybody for your patience and feedback on this one.

**Comment by sourstripe** [comment]
So this will disable anything that happens in a filtered deck?

I was thinking of something like if I select not to reschedule cards in a filtered deck it won't contribute to the data(the addon will ignore it) but everything else will still effect it.

I'm not sure if I'm making any sense here. 

Either way, I think it's good that you added the option. 

My other thought this how will this option interact with mobile reviews in filtered decks. Will it be able to know it was not a review when we go to adjust?

**Comment by brownbat** [comment]
If "reviews only" is on... then basically before the algorithm does anything, it says, "am I looking at a card in the review state?"

If so, to calculate all the averages and performance, it only pulls the history of card reps that were actually in the review state.

So the reschedule filtered options won't really come into play, it's currently all or nothing.

For mobile... if you're doing reviews on mobile, they'll get logged as reviews. If you do a filtered rep on mobile, it should get labeled with a different category in the log. So later, when you do a review on desktop, or if you use the deck options on desktop to reset ease factors to performance, it will grab only those true reviews on mobile for the calculation, but ignore filtered deck reps (from mobile or desktop).

I think the code is pretty clean, but there are a lot of permutations. Mobile/desktop. v2 scheduler/v1. Anki version. my testing could have missed some combination of these. Let me know if anything ends up looking funny.

**Comment by sourstripe** [comment]
> If "reviews only" is on... then basically before the algorithm does anything, it says, "am I looking at a card in the review state?"
> 
> If so, to calculate all the averages and performance, it only pulls the history of card reps that were actually in the review state.
> 
> So the reschedule filtered options won't really come into play, it's currently all or nothing.
> 
> For mobile... if you're doing reviews on mobile, they'll get logged as reviews. If you do a filtered rep on mobile, it should get labeled with a different category in the log. So later, when you do a review on desktop, or if you use the deck options on desktop to reset ease factors to performance, it will grab only those true reviews on mobile for the calculation, but ignore filtered deck reps (from mobile or desktop).
> 
> I think the code is pretty clean, but there are a lot of permutations. Mobile/desktop. v2 scheduler/v1. Anki version. my testing could have missed some combination of these. Let me know if anything ends up looking funny.

Thanks for your hard work! I'll keep an eye on it
