### ISSUE TITLE
ease is going down, even when I select the pass button

### ISSUE THREAD

**Issue by fjaieohfaufn** [brownbat/autoEaseFactor#62]
![image](https://user-images.githubusercontent.com/86940684/124413763-ebcc8400-dd16-11eb-8fbb-8856a7094411.png)

Started using this a few days ago. in attached screenshot, you can see that the ease is going down, even when I select the pass button (most recent reviews are on top).

I'm using Anki Version ⁨2.1.42

**Comment by Papierjaeger** [comment]
Ich think it's because it targets a success rate like 85%.
If your success rate is below 85% it goes down and if it goes above 85% it goes up.

**Comment by shiosai** [comment]
I was confused by the same in the beginning - its because of the _leash_. It cannot go down as far as it calculates when you fail but it will do so in the next checks even if you pass due to low moving average.

Its not very intuitive but that's just how it is. In the end its kinda competing in a way with your lapse interval as well. Until anki has a more holistic system I guess that's what we have to live with - basically forever as Anki will probably never get a better system :D
