### ISSUE TITLE
How much is the algorithm (and resulting interval) affected by the setting "new interval after a lapse"?

### ISSUE THREAD

**Issue by galantra** [brownbat/autoEaseFactor#67]
Context:

I've used [autoLapseNewInterval](https://github.com/daedsidog/Anki-autoLapseNewInterval) for a long time with a target setting of 85%. There is [a Supermemopedia article](https://supermemo.guru/wiki/Post-lapse_stability) that suggests that the “new interval” should actually be just a few days.

So, I am going to try out autoLapseNewInterval set to a 95% target.

I wonder how the “new interval” setting affects your add-on (which I've set to 85%)?

**Comment by Willz7** [comment]
@galantra 
I don't believe it will have an impact on the auto ease factor because the addon only focuses on the card individually ease whereas the auto lapse new interval feature concentrates on what lapse setting you should use in the "New Interval" when you first open Anki.

Does Auto Lapse New Interval only target a single deck, or does it also target each card separately?

**Comment by galantra** [comment]
The deck. It changes the value in the deck options.

Thank you for the answer. My concern was that a very short “new interval” might throw Auto Ease factor off since it changes the interval so drastically.
